const BLUR_FADE_DELAY = 0.04;
const BOX_REVEAL_DURATION = 0.4;

const DEFAULT_DISTANCE = 140;
const DEFAULT_MAGNIFICATION = 60;

export { BLUR_FADE_DELAY, BOX_REVEAL_DURATION, DEFAULT_DISTANCE, DEFAULT_MAGNIFICATION };
