const POST_SLICE_NUMBER = 4;
const PROJECT_SLICE_NUMBER = 4;
const PROJECTS_PER_PAGE = 8;
const BOOKS_PER_PAGE = 6;

export { POST_SLICE_NUMBER, PROJECT_SLICE_NUMBER, PROJECTS_PER_PAGE, BOOKS_PER_PAGE };
